export interface FormData {
    businessName: string;
    isIndividual: boolean;
    pocName: string;
    email: string;
    teamSize: string;
    bookingsPerYear: string;
    experience: string;
    vendorType: string[];
    categories: string[];
    city: string;
    serviceAreas: string[];
    profilePicture: string;
    description: string;
    businessPhotos: string[];
    coverImage: string;
}

export const INITIAL_FORM_DATA: FormData = {
    businessName: '',
    isIndividual: false,
    pocName: '',
    email: '',
    teamSize: '',
    bookingsPerYear: '',
    experience: '',
    vendorType: [],
    categories: [],
    city: '',
    serviceAreas: [],
    profilePicture: '',
    description: '',
    businessPhotos: [],
    coverImage: '',
};

export const TEAM_SIZE_OPTIONS = [
    '1 - 5 people', '6 - 15 people', '16 - 30 people', '31 - 50 people', '50+ people',
];

export const BOOKINGS_OPTIONS = [
    '0 - 24 bookings/year', '25 - 49 bookings/year', '50 - 74 bookings/year',
    '75 - 99 bookings/year', '100+ bookings/year',
];

export const EXPERIENCE_OPTIONS = [
    '0 - 2 years', '2 - 5 years', '5 - 8 years', '8 - 12 years', '12+ years',
];

export const VENDOR_TYPES = [
    'Caterer', 'Decorator', 'DJ Artist', 'Makeup Artist',
    'Photography and Videography', 'Venue Provider',
];

export const EVENT_CATEGORIES = [
    'Alumni Meet & Reunion',
    'Annaprashan (Rice Ceremony)',
    'Anniversary Celebration',
    'Art Exhibition & Opening',
    'Award Ceremony & Gala',
    'Baby Shower',
    'Bachelorette Party',
    'Baisakhi Celebration',
    'Bakrid (Eid ul-Adha)',
    'Beauty Pageant',
    'Bhandara',
    'Bihu Festival',
    'Birthday Party',
    'Book Launch & Literary Event',
    'Brand Activation Event',
    'Brand Launch Event',
    'Bridal Show & Wedding Expo',
    'Bridal Shower',
    'Buddha Purnima',
    'Business Conference & Summit',
    'Charity Gala & Fundraiser',
    'Chhath Puja',
    'Christmas Party',
    'Club Night & DJ Night',
    'College Annual Day & Fest',
    'College Farewell & Fresher\'s Party',
    'Comedy Show & Stand-Up Night',
    'Community Fair (Mela)',
    'Community Health & Wellness Camp',
    'Concert & Live Performance',
    'Corporate Annual Day',
    'Corporate Award Ceremony',
    'Corporate Offsite & Team Retreat',
    'Corporate Product Launch',
    'Corporate Sports Day',
    'Cultural Exhibition & Art Show',
    'Cultural Festival',
    'Dance Competition',
    'Dance Performance & Recital',
    'Dandiya & Garba Night',
    'Destination Wedding',
    'Diwali Party & Mela',
    'Durga Puja Celebration',
    'Dussehra Celebration',
    'Easter Celebration',
    'EDM & Rave Party',
    'Eid Get-Together',
    'Engagement Ceremony',
    'Esports & Gaming Tournament',
    'Exhibition & Trade Fair',
    'Farewell Party',
    'Fashion Show & Ramp Event',
    'Film & TV Award Night',
    'Film Premiere & Screening',
    'Flash Mob',
    'Food Festival & Culinary Event',
    'Ganesh Chaturthi Celebration & Pandal',
    'Ganesh Visarjan',
    'Gender Reveal Party',
    'Get-Together & Social Gathering',
    'Good Friday Observance',
    'Govardhan Puja',
    'Government Banquet & State Dinner',
    'Graduation & Convocation Ceremony',
    'Griha Pravesh (Housewarming)',
    'Gudi Padwa',
    'Guru Nanak Jayanti',
    'Guru Purnima',
    'Haldi Ceremony',
    'Hari Kirtan & Satsang',
    'Health & Fitness Expo',
    'Hemis Festival',
    'Heritage & History Walk',
    'Holi Celebration & Color Party',
    'Hornbill Festival',
    'House Party',
    'Iftar Party',
    'Inauguration Ceremony',
    'Independence Day & Republic Day Event',
    'Influencer Meetup',
    'Jagran & Religious Night',
    'Jain Paryushan Event',
    'Janmashtami Celebration',
    'Kali Puja',
    'Karaoke Night',
    'Karva Chauth Gathering',
    'Kitty Party',
    'Ladies Sangeet',
    'Lohri Celebration',
    'Maha Shivratri',
    'Mahavir Jayanti',
    'Makar Sankranti Party',
    'Makeup Competition',
    'Marathon & Run Event',
    'Mawlid (Eid-e-Milad)',
    'Mehndi Ceremony',
    'Movie Premiere & Press Meet',
    'Muharram',
    'Mundan Ceremony',
    'Music Festival',
    'Namkaran (Naming Ceremony)',
    'Navratri Garba Night',
    'Networking Event',
    'New Year\'s Eve Party',
    'Nikah Ceremony',
    'Office Party & Celebration',
    'Onam Celebration',
    'Photoshoot Event',
    'Pohela Boishakh',
    'Political Convention',
    'Pongal Celebration',
    'Pool Party',
    'Pre-Wedding Shoot',
    'Press Conference & Media Briefing',
    'Pride Parade & LGBTQ+ Event',
    'Product Launch Event',
    'Prom Night',
    'Puja & Pooja Ceremony',
    'Puja Pandal & Langar',
    'Qawwali & Sufi Night',
    'Raksha Bandhan',
    'Ram Navami',
    'Ramp Walk Competition',
    'Reunion Party',
    'Ring Ceremony',
    'Roka Ceremony',
    'Rooftop Party',
    'Sangeet Ceremony',
    'School Annual Day & Sports Day',
    'Seemantham Ceremony',
    'Seminar & Workshop',
    'Sports Tournament & Championship',
    'Startup Demo Day & Pitch Event',
    'Team Outing',
    'Technology & Innovation Expo',
    'TEDx & Speaker Event',
    'Teej Festival',
    'Themed Party (Bollywood / Retro / Masquerade)',
    'Thrissur Pooram',
    'Tilak Ceremony',
    'Ugadi Celebration',
    'Upanayana (Thread Ceremony)',
    'Vasant Panchami',
    'Vastu Puja',
    'Wedding',
    'Wellness & Yoga Retreat',
    'Welcome baby Event',
    'Yagna & Katha',
    'Youth Festival',
];

export const CITY_LOCALITIES: Record<string, string[]> = {
    Ghaziabad: ['Indirapuram', 'Vasundhara', 'Vaishali'],
    Delhi: ['Connaught Place', 'South Delhi', 'North Delhi', 'Dwarka', 'Saket'],
    Gurugram: ['DLF Phase 1', 'Sushant Lok', 'Golf Course Road', 'Sector 56'],
    Moradabad: ['Civil Lines', 'Ramganga Vihar', 'Kanth Road'],
    Meerut: ['Shastri Nagar', 'Modipuram', 'Pallavpuram'],
    Noida: ['Sector 18', 'Sector 62', 'Noida Extension', 'Sector 15'],
};

export const AVATARS = ['/images/male-avatar.png', '/images/female-avatar.png'];

export const CONTINUE_BUTTON_COLOR = 'rgba(4, 34, 45, 1)';
